theme: jekyll-theme-minimal
title: Yahya's homepage
description: I share here research projects and blogs thereon. 
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
page_excerpts: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
social-network-links: 
  stackoverflow: "9943046"
  linkedin: yahyasaleh
  twitter: @yahya_saleh94
![Hello World](/assets/images/stylized.png)
