theme: jekyll-theme-minimal
title: Yahya's homepage
description: I share here research projects and blogs thereon. 
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
page_excerpts: true
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
minima: 
  social_links: 
    stackoverflow: "9943046"
    linkedin: yahyasaleh
